Add switches
puzzle/home-assistant-config pull request #9
Opened 2019-06-21 12:09 UTC by rekup

Add additional myStrom switches and corresponding ui elements

2019-06-25 05:14 UTC, bliemli requested changes

2019-06-25 05:14 UTC, bliemli commented on customize.yaml
> +      friendly_name: 'Alte Kaffeemaschine'
What's meant with "Alte"? The Nespresso machine? If so I'd rather it was named that way :)

2019-07-09 07:03 UTC, rekup commented on customize.yaml
> +      friendly_name: 'Alte Kaffeemaschine'
Valid point. I changed the descriptions to something more meaningful

2019-07-09 15:29 UTC, bliemli approved these changes

2019-07-09 15:29 UTC, merged